Drop Table Cities;
Drop table Countries;

Create Table Countries (
  id int primary key generated by default as identity,
  name varchar(50),
  capital varchar(50),
  population double precision
);

Insert Into countries(NAME, CAPITAL, POPULATION) values ('Armenia', 'Yerevan', 2.7);
Insert Into countries(NAME, CAPITAL, POPULATION) values ('Australia', 'Kanberra', 26.4);
Insert Into countries(NAME, CAPITAL, POPULATION) values ('China', 'Beijing', 1425.7);
Insert Into countries(NAME, CAPITAL, POPULATION) values ('France', 'Paris', 65.5);
Insert Into countries(NAME, CAPITAL, POPULATION) values ('India', 'New Delhi', 1428.6);
Insert Into countries(NAME, CAPITAL, POPULATION) values ('Russia', 'Moscow', 145.1);
Insert Into countries(NAME, CAPITAL, POPULATION) values ('Ukraine', 'Kyjv', 36.7);

Create Table Cities (
  id int primary key generated by default as identity,
  name varchar(50),
  population double precision,
  country_id int
);

alter table Cities add constraint FK_CITIES_COUNTRIES foreign key (COUNTRY_ID) references COUNTRIES